version: '3.7'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - SA_PASSWORD=Strong@Password1234567890@#$
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - backend

volumes:
  sqlserverdata:
    driver: local

networks:
  backend:
    driver: bridge